import { FeedContent } from "./content";

/**
 * A small deterministic dataset of realistic‑looking content.
 * The data is deliberately diverse so that the scoring algorithm can be
 * exercised with many different interest and content‑type combinations.
 */
export const MOCK_CONTENT: FeedContent[] = [
  {
    id: "1",
    title: "Why smaller AI models are becoming surprisingly capable",
    description: "A look at how efficient models are achieving performance previously reserved for massive architectures.",
    category: "Technology",
    interests: ["ai", "programming"],
    contentType: "educational",
    image: "/images/ai-models.png",
    source: "TechCrunch",
    filterTags: [],
  },
  {
    id: "2",
    title: "A practical guide to building a REST API with Node.js",
    description: "Step‑by‑step tutorial covering routing, authentication and deployment.",
    category: "Programming",
    interests: ["programming", "ai"],
    contentType: "tutorials",
    image: "/images/node-api.png",
    source: "Dev.to",
    filterTags: [],
  },
  {
    id: "3",
    title: "How passkeys are changing authentication",
    description: "Explains the security benefits of password‑less logins and how they work.",
    category: "Security",
    interests: ["cybersecurity", "technology"],
    contentType: "educational",
    image: "/images/passkeys.png",
    source: "Wired",
    filterTags: [],
  },
  {
    id: "4",
    title: "Why game engines are moving toward procedural worlds",
    description: "Procedural generation lets studios create massive, varied environments with less manual effort.",
    category: "Gaming",
    interests: ["gaming", "technology"],
    contentType: "news",
    image: "/images/procedural.png",
    source: "The Verge",
    filterTags: [],
  },
  {
    id: "5",
    title: "Design trends for modern web interfaces in 2024",
    description: "An overview of colour palettes, typography and layout patterns gaining traction.",
    category: "Design",
    interests: ["design", "technology"],
    contentType: "educational",
    image: "/images/web-design.png",
    source: "Smashing Magazine",
    filterTags: [],
  },
  {
    id: "6",
    title: "Exploring the latest discoveries in quantum computing",
    description: "What recent breakthroughs mean for the future of computation.",
    category: "Science",
    interests: ["science", "ai"],
    contentType: "news",
    image: "/images/quantum.png",
    source: "Nature",
    filterTags: [],
  },
  {
    id: "7",
    title: "Tips for protecting your online privacy",
    description: "Practical steps you can take today to reduce tracking and data leaks.",
    category: "Security",
    interests: ["cybersecurity"],
    contentType: "tutorials",
    image: "/images/privacy.png",
    source: "EFF",
    filterTags: [],
  },
  {
    id: "8",
    title: "The rise of indie game development on mobile platforms",
    description: "How small studios are leveraging app stores to reach global audiences.",
    category: "Gaming",
    interests: ["gaming", "programming"],
    contentType: "entertainment",
    image: "/images/indie-game.png",
    source: "Polygon",
    filterTags: ["Celebrity content"], // example filter tag
  },
  {
    id: "9",
    title: "Understanding NFTs and their impact on digital art",
    description: "A balanced look at the technology, market, and cultural implications.",
    category: "Art",
    interests: ["design", "technology"],
    contentType: "discussion",
    image: "/images/nft.png",
    source: "Ars Technica",
    filterTags: ["Promotional content"],
  },
  // Add a few more items to reach ~15‑20 entries
  {
    id: "10",
    title: "Financial basics for tech professionals",
    description: "How to manage taxes, investments and retirement as a software engineer.",
    category: "Business",
    interests: ["business", "technology"],
    contentType: "educational",
    image: "/images/fin-tech.png",
    source: "Financial Times",
    filterTags: [],
  },
  {
    id: "11",
    title: "SpaceX's latest Starship test flight",
    description: "Details on the launch, performance metrics and future plans.",
    category: "Space",
    interests: ["space", "technology"],
    contentType: "news",
    image: "/images/starship.png",
    source: "Space.com",
    filterTags: [],
  },
  {
    id: "12",
    title: "Creative photography tips for low‑light conditions",
    description: "Learn how to capture sharp, vibrant images when the light is scarce.",
    category: "Photography",
    interests: ["photography", "design"],
    contentType: "tutorials",
    image: "/images/low-light.png",
    source: "Digital Photography Review",
    filterTags: [],
  },
  {
    id: "13",
    title: "The future of renewable energy technologies",
    description: "Analyzes solar, wind and emerging storage solutions.",
    category: "Science",
    interests: ["science", "technology"],
    contentType: "educational",
    image: "/images/renewable.png",
    source: "MIT Technology Review",
    filterTags: [],
  },
];
